# Generated by Django 3.1.5 on 2021-01-26 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='feedback',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(40), django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
